service: tasks-api

frameworkVersion: '3'
useDotenv: true


provider:
  name: aws
  runtime: python3.11
  region: ${opt:region, 'ap-northeast-1'}
  stage: ${opt:stage, 'development'}
  logRetentionInDays: 30
  environment:
    APP_ENVIRONMENT: ${self:provider.stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          # Allow only access to the API's table and its indexes
          Resource:
            - "Fn::GetAtt": [ TasksAPITable, Arn ]
            - "Fn::Join": ['/', ["Fn::GetAtt": [ TasksAPITable, Arn ], 'index', '*']]

functions:
  API:
    handler: main.handle
    timeout: 10
    memorySize: 512
    events:
      - http:
          path: /{proxy+}
          method: any
          cors:
            origin: ${env:ALLOWED_ORIGINS}
            maxAge: 60


custom:
  pythonRequirements:
    usePoetry: true
    noDeploy:
      - boto3 # already in Lambda
      - botocore # already in Lambda
  stage: ${opt:stage, self:provider.stage}
  tableName: ${self:custom.stage}-tasks-api

plugins:
  - serverless-python-requirements

resources:
  - ${file(resources/dynamodb.yml)}